version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3307:3306'
    environment:
       MYSQL_DATABASE: 'toolbox'
       MYSQL_USER: 'acacia'
       MYSQL_PASSWORD: 'Beaumont1'
       MYSQL_ROOT_PASSWORD: 'Beaumont1'

  web:
    build: .
    working_dir: /code
    command: /bin/bash -c "mysql -hdb -uacacia -pBeaumont1 toolbox < db.sql && python toolbox/manage.py runserver 0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

